### ISSUE TITLE
Froala Editor issue

### ISSUE THREAD

**Issue by vselva3x** [MooDySmiles/moodysmiles.github.io#1]
I am facing the same issue 

Can u help me to give the exact code that you fix this issue?

**Comment by MooDySmiles** [comment]
Hi? I think this question should have been done on the issue you mentioned, and not on someone personal repo 😄 

With that said, it's not much more of what I and *APet74* haven't already said in that issue.

In my component file I have some data retrieving via `resolver` like

```typescript
ngOnInit() {
  this.route.data.pipe(
    tap((data) => this.data = data),
  ).subscribe();
}
```

and in my template file I have the editor displaying like

```html
<div class="container">
  <div
    [froalaEditor]="froalaOptions"
    [(froalaModel)]="value"
    (froalaModelChange)="onModelChange($event)"
  ></div>
```
